#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
xset r rate 350 20 &
$HOME/.config/polybar/launch.sh &
dunst -conf $HOME/.config/dunst/dunstrc &
picom &
feh --bg-fill --no-xinerama ~/Pictures/lain-3.jpg
xrdb merge ~/.Xresources &
ibus-daemon -drxR &
~/bin/battery-alert &
nm-applet &
#

# dual monitor setup

INTERNAL_MONITOR="eDP1"
EXTERNAL_MONITOR="HDMI2"
if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
  xrandr --output eDP1 --primary --mode 1920x1080 --rotate normal --output HDMI2 --mode 1920x1080 --rotate normal --above eDP1
fi

if [[ "$1" = 0 ]]; then
  if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5
    bspc monitor "$EXTERNAL_MONITOR" -d 6 7 
    bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
  else
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7
  fi
fi

monitor_add() {
  # Move first 5 desktops to external monitor
  for desktop in $(bspc query -D --names -m "$INTERNAL_MONITOR" | sed 5q); do
    bspc desktop "$desktop" --to-monitor "$EXTERNAL_MONITOR"
  done

  # Remove default desktop created by bspwm
  bspc desktop Desktop --remove

  # reorder monitors
  bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
}

monitor_remove() {
  # Add default temp desktop because a minimum of one desktop is required per monitor
  bspc monitor "$EXTERNAL_MONITOR" -a Desktop

  # Move all desktops except the last default desktop to internal monitor
  for desktop in $(bspc query -D -m "$EXTERNAL_MONITOR");	do
    bspc desktop "$desktop" --to-monitor "$INTERNAL_MONITOR"
  done

  # delete default desktops
  bspc desktop Desktop --remove

  # reorder desktops
  bspc monitor "$INTERNAL_MONITOR" -o 1 2 3 4 5 6 7 8 9 10
}


if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
  # set xrandr rules for docked setup
  xrandr --output "$INTERNAL_MONITOR" --mode 1920x1080 --pos 0x0 --rotate normal --output "$EXTERNAL_MONITOR" --primary --mode 1920x1080 --pos 1920x0 --rotate normal --above eDP1
  if [[ $(bspc query -D -m "${EXTERNAL_MONITOR}" | wc -l) -ne 5 ]]; then
    monitor_add
  fi
  bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
else
  # set xrandr rules for mobile setup
  xrandr --output "$INTERNAL_MONITOR" --primary --mode 1920x1080 --pos 0x0 --rotate normal --output "$EXTERNAL_MONITOR" --off
  if [[ $(bspc query -D -m "${INTERNAL_MONITOR}" | wc -l) -ne 10 ]]; then
    monitor_remove
  fi
fi

bspc config border_width        0
bspc config window_gap          18

bspc config focused_border_color \#c0caf5

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a firefox-developer-edition desktop=^2
bspc rule -a discord desktop=^3
bspc config external_rules_command "$HOME/bin/spotify-rule"

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

